import { GoogleGenAI } from "@google/genai";
import { PhotoType, PHOTO_CONFIGS } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateIDPhoto = async (
  base64Image: string,
  type: PhotoType
): Promise<string> => {
  try {
    const config = PHOTO_CONFIGS[type];
    const prompt = `
      Edit this image to create a professional ${type} photo.
      Tasks:
      1. Identify the person in the provided image.
      2. Change their clothing to a ${config.clothing}. The fit should be perfect and realistic.
      3. Change the background to a ${config.bgColor}.
      4. Ensure the face is centered, lighting is soft and even (studio quality).
      5. Maintain the person's exact facial identity and features.
      6. Output a high-quality, photorealistic image suitable for official documents.
      7. Aspect ratio should be portrait (approx 3:4 or 4:5).
    `;

    // Remove data:image/...;base64, prefix if present
    const base64Data = base64Image.split(',')[1] || base64Image;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: base64Data
            }
          },
          { text: prompt }
        ]
      }
    });

    // Extract the image from the response
    let generatedImageUrl = '';
    if (response.candidates && response.candidates[0] && response.candidates[0].content && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!generatedImageUrl) {
      throw new Error("No image generated by the model.");
    }

    return generatedImageUrl;

  } catch (error) {
    console.error("Error generating photo:", error);
    throw error;
  }
};